export const schools: Array<string> = [
    "Agriculture, Food and Wine",
    "Architecture and Civil Engineering",
    "Biological Sciences",
    "Chemical Engineering",
    "Computer and Mathematical Sciences",
    "Electrical and Mechanical Engineering",
    "Physics, Chemistry and Earth Sciences",
    "Animal and Veterinary Sciences",
    "Dental",
    "Medical",
    "Nursing",
    "Rural Clinical",
    "Allied Health Science and Practice",
    "Biomedicine",
    "Psychology",
    "Public Health",
    "Business",
    "Music",
    "Law",
    "Economics and Public Policy",
    "Education",
    "Humanities",
    "Social Sciences"
];